### PR TITLE
(PA-4813) Refresh CA certs & generate FIPS compatible keystore

### PR DESCRIPTION
**Pull request by joshcooper**
Updates the `prepare` target to generate a FIPS java keystore `puppet-cacerts-fips`

Adds an `install-fips` make target to install the fips keystore. Currently both the FIPS and non-FIPS keystores are copied to the same destination, so they are mutually exclusive.

Refreshes the list of CA certs (some additions and removals):

```
$ git diff --summary 34e5dfc..HEAD | grep .crt
 create mode 100644 Atos_TrustedRoot_Root_CA_ECC_TLS_2021:2.16.61.152.59.166.102.61.144.99.247.126.38.87.56.4.239.0.crt
 create mode 100644 Atos_TrustedRoot_Root_CA_RSA_TLS_2021:2.16.83.213.207.230.25.147.11.251.43.5.18.216.194.42.162.164.crt
 create mode 100644 BJCA_Global_Root_CA1:2.16.85.111.101.227.180.217.144.106.27.9.209.108.62.192.108.32.crt
 create mode 100644 BJCA_Global_Root_CA2:2.16.44.23.8.125.100.42.192.254.133.24.89.6.207.180.74.235.crt
 create mode 100644 Certainly_Root_E1:2.16.6.37.51.177.71.3.51.39.92.249.141.154.185.191.204.248.crt
 create mode 100644 Certainly_Root_R1:2.17.0.142.15.249.75.144.113.104.101.51.84.244.212.68.57.183.224.crt
 create mode 100644 DigiCert_TLS_ECC_P384_Root_G5:2.16.9.224.147.101.172.247.217.200.185.62.28.11.4.42.46.243.crt
 create mode 100644 DigiCert_TLS_RSA4096_Root_G5:2.16.8.249.180.120.168.250.126.218.106.51.55.137.222.124.207.138.crt
 delete mode 100644 E-Tugra_Certification_Authority:2.8.106.104.62.156.81.155.203.83.crt
 delete mode 100644 EC-ACC:2.16.238.43.61.235.212.33.222.20.168.98.172.4.243.221.196.1.crt
 delete mode 100644 Hellenic_Academic_and_Research_Institutions_RootCA_2011:2.1.0.crt
 delete mode 100644 Hongkong_Post_Root_CA_1:2.2.3.232.crt
 delete mode 100644 Network_Solutions_Certificate_Authority:2.16.87.203.51.111.194.92.22.230.71.22.23.227.144.49.104.224.crt
 create mode 100644 SSL.com_TLS_ECC_Root_CA_2022:2.16.20.3.245.171.251.55.139.23.64.91.226.67.178.165.209.196.crt
 create mode 100644 SSL.com_TLS_RSA_Root_CA_2022:2.16.111.190.218.173.115.189.8.64.226.139.77.190.212.247.91.145.crt
 create mode 100644 Sectigo_Public_Server_Authentication_Root_E46:2.16.66.242.204.218.27.105.55.68.95.21.254.117.40.16.184.244.crt
 create mode 100644 Sectigo_Public_Server_Authentication_Root_R46:2.16.117.141.253.139.174.124.7.0.250.169.37.167.225.199.173.20.crt
 create mode 100644 Security_Communication_ECC_RootCA1:2.9.0.214.93.155.179.120.129.46.235.crt
 create mode 100644 Security_Communication_RootCA3:2.9.0.225.124.55.64.253.27.254.103.crt
 delete mode 100644 Staat_der_Nederlanden_EV_Root_CA:2.4.0.152.150.141.crt
```

### CODE REVIEW

**Comment by joshcooper** [comment]
I verified the FIPS cert bundle is loadable using 

```java
import java.io.*;
import java.security.*;

class Fips {
  	public static void main(String[] args) throws Exception {
        KeyStore keyStore = KeyStore.getInstance("BCFKS");
        try (FileInputStream fis = new FileInputStream("/etc/puppetlabs/puppet/ssl/puppet-cacerts")) {
            keyStore.load(fis, "changeit".toCharArray());
        }
        System.out.println("keystore contains " + keyStore.size() + " entries");
    }
}
```

```
[root@only-depth ~]# javac Fips.java
[root@only-depth ~]# /opt/puppetlabs/server/bin/java -Djava.security.properties=/opt/puppetlabs/share/jdk11-fips-security -cp .:/opt/puppetlabs/share/java/bc-fips.jar Fips
keystore contains 141 entries
```

**Review by e-gris — APPROVED** [review]
I'm giving my approval with the caveat that I've never seen this repo before nor do I know what it does.

However, I suspect that's true for all of us. We may want to reconsider ownership.

**Comment by joshcooper** [comment]
> nor do I know what it does.

We ship a CA bundle in puppet-agent because many of our platforms (at the time) didn't have a current `ca-certificates` bundle (Windows, AIX, Solaris and old Linux). So this repo is used to create a PEM and Java keystores, which are shipped in puppet-runtime https://github.com/puppetlabs/puppet-runtime/blob/57dfe7f279dec07aff29cdc0ce13e919f9a0cd3a/configs/components/puppet-ca-bundle.json#L2

> We may want to reconsider ownership

I'll push up a separate PR

**Comment by joshcooper** [comment]
Submitted https://github.com/puppetlabs/puppet-ca-bundle/pull/20

**Pull request merged**
